# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['add', 'foo']

# %% ../nbs/00_core.ipynb 7
def add(x,y):
    return x+y

# %% ../nbs/00_core.ipynb 8
def foo(): pass
